package utils.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import lombok.Getter;
import lombok.Setter;
import utils.utils.PriceCalculatorUtils;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Getter
@Setter
@DynamoDBTable(tableName = "UcionicaStays")
public class StaysTable {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute(attributeName = "userId")
    private String userId;
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime startTime;
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime endTime;
    @DynamoDBAttribute(attributeName = "price")
    private BigDecimal price;

    public void setPrice() {
        this.price = PriceCalculatorUtils.getPrice(startTime, endTime);
    }
}