Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 2048
      Handler: users.GetHighestDebts
      CodeUri: /Users/frankomlinovic/IdeaProjects/Ucionica/Users
      Runtime: java11
      Architectures:
        - x86_64