Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 1152
      Handler: stays.GetCurrentStays
      CodeUri: /Users/frankomlinovic/IdeaProjects/Ucionica/Stays
      Runtime: java11
      Architectures:
        - x86_64